services:
  frapast:
    build:
      context: .
      dockerfile: Dockerfile
    image: frapast/engine:latest
    container_name: frapast-engine
    volumes:
      - .:/scan
    environment:
      - FRAPAST_BENCH_URL=http://bench:8000
    command: ["scan", "/scan", "--severity"]

  bench:
    image: frappe/frappe-worker:v15.0.0
    container_name: frapast-bench-worker
    ports:
      - "8000:8000"
    environment:
      - MARIADB_HOST=db
      - REDIS_CACHE=redis://redis:6379
    depends_on:
      - db
      - redis

  db:
    image: mariadb:10.6
    container_name: frapast-db
    environment:
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "3306:3306"

  redis:
    image: redis:7-alpine
    container_name: frapast-redis
    ports:
      - "6379:6379"
